marina:
  topyacht:
    url: "http://www.topyacht.com.au/mt/boat_list.php"
    boat-detail: "http://www.topyacht.com.au/mt/mt_pub.php?boid="
    boat-photo: "http://www.topyacht.com.au/mt/mt_photo.php?boid="
  photos:
    path: "/data/photos-combined/"
  security:
    jwtCookieName: otb
    jwtSecret: yAwfZ2TvTolMoaeF0LY4OyMtihSvpUWHwmnOTAWzLXM7rwCQpE7Ca1+VT6n4BSZG9XFkH1EeMVFItLy2Cw9jXJK0pPxgXW+vcFSn2zbhqyS2dyf2Ro2btDBiczevBWSp
    jwtExpirationMs: 86400000
server:
  servlet:
    context-path: "/api"
spring:
  datasource:
    url: jdbc:h2:file:./data/backend.db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  hibernate:
    dialect: org.hibernate.dialect.H2Dialect
  jpa:
    #    properties.hibernate:
    #      show_sql: true
    #      use_sql_comments: true
    #      format_sql: true
    hibernate:
      ddl-auto: update
  security:
    filter:
      dispatcher-types:
        - request
        - error
logging:
  level:
    org:
      springframework:
        security: TRACE

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days


jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub