marina:
  topyacht:
    url: "http://www.topyacht.com.au/mt/boat_list.php"
    boat-detail: "http://www.topyacht.com.au/mt/mt_pub.php?boid="
    boat-photo: "http://www.topyacht.com.au/mt/mt_photo.php?boid="
  photos:
    path: "/data/photos-combined/"
server:
  servlet:
    context-path: "/api"
spring:
  datasource:
    url: jdbc:h2:file:./data/backend.db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  hibernate:
    dialect: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      ddl-auto: update

